# See https://www.zigbee2mqtt.io/guide/configuration/.
# NOTE: Zigbee2MQTT writes to this file.

# Indicates the configuration version (used by configuration migrations).
version: 4

# Allow new devices to join.
# TODO: It's important to disable this after you've peered your devices!
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages.
  base_topic: zigbee2mqtt
  # MQTT server URL.
  server: mqtt://localhost:1883
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: '!secret.yaml mqtt_password'

# Serial settings, only required when Zigbee2MQTT fails to start with:
#   USB adapter discovery error (No valid USB adapter found).
# serial:
#     # Location of the adapter
#     # USB adapters - use format "port: /dev/serial/by-id/XXX"
#     # Ethernet adapters - use format "port: tcp://192.168.1.12:6638"
#     port: /dev/ttyACM0
#     # Adapter type, allowed values: `zstack`, `ember`, `deconz`, `zigate` or `zboss`
#     adapter: zstack

# Built-in web-based frontend
frontend:
  enabled: true
  # Port to listen on.
  port: 8080
  # Host to listen on, it can also be a unix socket path.
  host: 127.0.0.1
  # Optionally enable authentication (add 'auth_token: PASSWORD' to secret.yaml).
  # auth_token: '!secret.yaml auth_token'
  # Optional URL on which the frontend can be reached, currently only used for
  # the Home Assistant device configuration page.
  # url: https://zigbee2mqtt.example.org

# Availability feature
availability:
  enabled: false

# Home Assistant integration (MQTT discovery)
homeassistant:
  enabled: false

advanced:
  log_level: info
  # TIP: If you prefer logging to a file, replace "syslog" with "file" and
  # create the log directory:
  # `install -d -m750 -o zigbee2mqtt -g zigbee2mqtt /var/log/zigbee2mqtt`
  log_output:
    - console
    - syslog
  log_directory: /var/log/zigbee2mqtt
  log_syslog:
    facility: daemon
    path: /dev/log
    protocol: unix
  # Zigbee network encryption key for better security.
  network_key: '!secret.yaml network_key'
  # ZigBee pan ID.
  pan_id: '!secret.yaml pan_id'

# The following file paths are relative to the datadir (/var/lib/zigbee2mqtt).
devices: devices.yaml
groups: groups.yaml

# Block devices from the network (by ieeeAddr).
blocklist: []
